### ISSUE TITLE
Can't update a column to null

### ISSUE THREAD

**Issue by AbhinavOmprakash** [hettie-d/pg_bitemporal#4]
Hi Hettie, 
We found a small problem.

PG-version 13 

# Description
 Updating a column to null fails when the column is of type other than text. 

# Example for reproduction 

```sql
select * from bitemporal_internal.ll_create_bitemporal_table(
    'common',
    'person',
  $$id int not null,
    name text,
    phone_number int$$,
  $$id$$
);

select bitemporal_internal.ll_bitemporal_insert('common.person', 
                                                $$id, name, phone_number$$, 
                                                $$1,'john doe', 0123456789$$,
                                                temporal_relationships.timeperiod(now(), 'infinity'),
                                                temporal_relationships.timeperiod(now(), 'infinity'));

=> select * from person;
 person_key | id |   name   | phone_number |                 effective                  |                  asserted                  |        row_created_at
------------+----+----------+--------------+--------------------------------------------+--------------------------------------------+-------------------------------
          1 |  1 | john doe |    123456789 | ["2022-04-20 07:48:18.634407+00",infinity) | ["2022-04-20 07:48:18.634407+00",infinity) | 2022-04-20 07:48:18.634407+00

-- Then we update the phone number to null

=> select bitemporal_internal.ll_bitemporal_update('common','person',
                                                 $$phone_number$$,
                                                 $$null$$,
                                                 $$id$$,
                                                 $$1$$,
                                                 temporal_relationships.timeperiod(now(), 'infinity'),
                                                 temporal_relationships.timeperiod(now(), 'infinity'));

ERROR:  column "phone_number" is of type integer but expression is of type text
LINE 1:  UPDATE common.person SET (phone_number) = (select null )
                                                           ^
HINT:  You will need to rewrite or cast the expression.
QUERY:   UPDATE common.person SET (phone_number) = (select null )
                    WHERE ( person_key )in ( 5 )
CONTEXT:  PL/pgSQL function bitemporal_internal.ll_bitemporal_update(text,text,text,text,text,text,temporal_relationships.timeperiod,temporal_relationships.timeperiod) line 89 at EXECUTE
```

We appreciate your help. Thanks.

**Comment by hettie-d** [comment]
Hi @AbhinavOmprakash , the actual workaround would be to explicitly cast NULL to the type. The problem is not easy to fix, and reason for the problem is that since PG 10, the updates using the list are not allowed in Postgres (previously you could write something like 

UPDATE table1 set (col1, col2)= (val1, val2)

That resulted in a workaround inside this function, and now that I think about it, the better option would be to make the function consistent with Postgres syntax, and not allow multiple column updates in this function, but use "update as select" instead.

For now, the write function invocation will be the following:

select bitemporal_internal.ll_bitemporal_update('common','person',
                                                 $$phone_number$$,
                                                 $$null::int$$,
                                                 $$id$$,
                                                 $$1$$,
                                                 temporal_relationships.timeperiod(now(), 'infinity'),
                                                 temporal_relationships.timeperiod(now(), 'infinity'));
I am so glad that you guys are exploring this repo and finding all these bugs. I would be happy to assist and advise you with your project (feel free to send me a connect request on LinkedIn for direct communications)
